
const centro = document.querySelector('.centro')
let level = 0
var conjPalavras = [] 
var palavra = ""
let chances = 5  
let ogame = true
let charEspec = false


const palavras = [ 

    ["flamengo"               , "time brasileiro", "futebol"   ],
    ["fluminense  "           , "time brasileiro", "futebol"   ],
    ["botafogo"               , "time brasileiro", "futebol"   ],
    ["américa"                , "time brasileiro", "futebol"   ],
    ["resende"                , "time brasileiro", "futebol"   ],
    ["bangu"                  , "time brasileiro", "futebol"   ],
    ["friburguense"           , "time brasileiro", "futebol"   ],
    ["boa vista"              , "time brasileiro", "futebol"   ],
    ["madureira"              , "time brasileiro", "futebol"   ],
    ["corinthians"            , "time brasileiro", "futebol"   ],
    ["são Paulo"              , "time brasileiro", "futebol"   ],
    ["palmeiras"              , "time brasileiro", "futebol"   ],
    ["santos"                 , "time brasileiro", "futebol"   ],
    ["red bull bragantino"    , "time brasileiro", "futebol"   ],
    ["portuguesa"             , "time brasileiro", "futebol"   ],
    ["guaraní"                , "time brasileiro", "futebol"   ],
    ["ponte preta"            , "time brasileiro", "futebol"   ],
    ["ituano"                 , "time brasileiro", "futebol"   ],
    ["internacional"          , "time brasileiro", "futebol"   ],
    ["grêmio"                 , "time brasileiro", "futebol"   ],
    ["juventude"              , "time brasileiro", "futebol"   ],
    ["criciuma"               , "time brasileiro", "futebol"   ],
    ["avai"                   , "time brasileiro", "futebol"   ],
    ["paraná"                 , "time brasileiro", "futebol"   ],
    ["atlético paranaense"    , "time brasileiro", "futebol"   ],
    ["coritiba"               , "time brasileiro", "futebol"   ],
    ["atlético mineiro"       , "time brasileiro", "futebol"   ],
    ["ipatinga"               , "time brasileiro", "futebol"   ],
    ["américa mineiro "       , "time brasileiro", "futebol"   ],
    ["cruzeiro"               , "time brasileiro", "futebol"   ],
    ["goiás"                  , "time brasileiro", "futebol"   ],
    ["brasiliense"            , "time brasileiro", "futebol"   ],
    ["gama"                   , "time brasileiro", "futebol"   ],
    ["atlético goianiense"    , "time brasileiro", "futebol"   ],
    ["bahia"                  , "time brasileiro", "futebol"   ],
    ["sport"                  , "time brasileiro", "futebol"   ],
    ["vitória"                , "time brasileiro", "futebol"   ],
    ["santa cruz"             , "time brasileiro", "futebol"   ],
    ["nautico"                , "time brasileiro", "futebol"   ],
    ["csa"                    , "time brasileiro", "futebol"   ],
    ["asa de arapiraca"       , "time brasileiro", "futebol"   ],
    ["crb"                    , "time brasileiro", "futebol"   ],
    ["ceará"                  , "time brasileiro", "futebol"   ],
    ["fortaleza"              , "time brasileiro", "futebol"   ],
    ["paysandu"               , "time brasileiro", "futebol"   ],
    ["remo"                   , "time brasileiro", "futebol"   ],
    ["cuiabá"                 , "time brasileiro", "futebol"   ],
    ["boca juniors"           , "time argentino", "futebol"    ],
    ["river plate"            , "time argentino", "futebol"    ],
    ["lanús"                  , "time argentino", "futebol"    ],
    ["newells old boys "      , "time argentino", "futebol"    ],
    ["racing"                 , "time argentino", "futebol"    ],
    ["san lorenzo"            , "time argentino", "futebol"    ],
    ["independiente"          , "time argentino", "futebol"    ],
    ["vélez sársfield"        , "time argentino", "futebol"    ],
    ["nacional"               , "time uruguaio", "futebol"     ],
    ["peñarol"                , "time uruguaio", "futebol"     ],
    ["alianza lima"            , "time peruano", "futebol"     ],
    ["sporting cristal"        , "time peruano", "futebol"     ],
    [" olimpia"                , "time paraguaio", "futebol"   ],
    ["libertad"                , "time paraguaio", "futebol"   ],
    ["cerro porteño"           , "time paraguaio", "futebol"   ],
    ["bolívar"                 , "time boliviano", "futebol"   ],
    ["jorge wilstermann"       , "time boliviano", "futebol"   ],
    ["the strongest"           , "time boliviano", "futebol"   ],
    ["oriente petrolero"       , "time boliviano", "futebol"   ],
    ["real potosí"             , "time boliviano", "futebol"   ],
    ["américa de cali "        , "time colombiano", "futebol"  ],
    ["tolima"                  , "time colombiano", "futebol"  ],
    ["millonarios"             , "time colombiano", "futebol"  ],
    ["atlético nacional"       , "time colombiano", "futebol"  ],
    ["deportivo cali"          , "time colombiano", "futebol"  ],
    ["deportivo Lara "         , "time venezuelano", "futebol" ],
    ["deportivo Táchira"       , "time venezuelano", "futebol" ],
    ["zamora"                  , "time venezuelano", "futebol" ],
    ["barcelona de guayaquil " , "time equatoriano", "futebol" ],
    ["ldu"                     , "time equatoriano", "futebol" ],
    ["emelec"                  , "time equatoriano", "futebol" ],
    ["deportivo cuenca"        , "time equatoriano", "futebol" ],
    ["colo-colo"              , "time chileno", "futebol"      ],
    ["universidad católica"   , "time chileno", "futebol"      ],
    ["universidad de chile"   , "time chileno", "futebol"      ],
    ["cobreloa"               , "time chileno", "futebol"      ],
    ["colo-colo"              , "time mexicano", "futebol"     ],
    ["universidad católica"   , "time mexicano", "futebol"     ],
    ["universidad de chile"   , "time mexicano", "futebol"     ],
    ["cobreloa"               , "time mexicano", "futebol"     ],
    ["américa do méxico"      , "time mexicano", "futebol"     ],
    ["chivas guadalajara"     , "time mexicano", "futebol"     ],
    ["toluca"                 , "time mexicano", "futebol"     ],
    ["cruz azul"              , "time mexicano", "futebol"     ],
    ["león"                   , "time mexicano", "futebol"     ],
    ["tigres"                 , "time mexicano", "futebol"     ],
    ["pachuca"                , "time mexicano", "futebol"     ],
    ["monterrey"              , "time mexicano", "futebol"     ],
    ["tijuana"                , "time mexicano", "futebol"     ],
    ["porto"                  , "time português", "futebol"    ],
    ["benfica"                , "time português", "futebol"    ],
    ["sporting braga"         , "time português", "futebol"    ],
    ["braga"                  , "time português", "futebol"    ],
    ["barcelona"              , "time espanhol", "futebol"     ],
    ["real madrid"            , "time espanhol", "futebol"     ],
    ["atlético de madrdi"     , "time espanhol", "futebol"     ],
    ["real sociedad"          , "time espanhol", "futebol"     ],
    ["espanyol"               , "time espanhol", "futebol"     ],
    ["betis"                  , "time espanhol", "futebol"     ],
    ["sevilla"                , "time espanhol", "futebol"     ],
    ["valencia"               , "time espanhol", "futebol"     ],
    ["manchester united"      , "time inglês", "futebol"       ],
    ["manchester city"        , "time inglês", "futebol"       ],
    ["liverpool"              , "time inglês", "futebol"       ],
    ["chelsea"                , "time inglês", "futebol"       ],
    ["arsenal"                , "time inglês", "futebol"       ],
    ["new castle"             , "time inglês", "futebol"       ],
    ["leicester"              , "time inglês", "futebol"       ],
    ["everton"                , "time inglês", "futebol"       ],
    ["paris saint-germain"    , "time francês", "futebol"      ],
    ["monaco"                 , "time francês", "futebol"      ],
    ["lyon"                   , "time francês", "futebol"      ],
    ["olympique de marseille" , "time francês", "futebol"      ],
    ["saint-étienne"          , "time francês", "futebol"      ],
    ["Nantes"                 , "time francês", "futebol"      ],
    ["bordeaux"               , "time francês", "futebol"      ],
    ["bayer leverkusen"         , "time alemão", "futebol"     ],
    ["bayern de munique"        , "time alemão", "futebol"     ],
    ["borussia dortmund"        , "time alemão", "futebol"     ],
    ["borussia mönchengladbach" , "time alemão", "futebol"     ],
    ["leipzig"                  , "time alemão", "futebol"     ],
    ["frankfurt"                , "time alemão", "futebol"     ],
    ["schalke"                  , "time alemão", "futebol"     ],
    ["werder bremen"            , "time alemão", "futebol"     ],
    ["wolfsburg"                , "time alemão", "futebol"     ],
    ["milan"                  , "time italiano", "futebol"     ],
    ["internazionale"         , "time italiano", "futebol"     ],
    ["juventus"               , "time italiano", "futebol"     ],
    ["roma"                   , "time italiano", "futebol"     ],
    ["lazio"                  , "time italiano", "futebol"     ],
    ["napoli"                 , "time italiano", "futebol"     ],
    ["torino"                 , "time italiano", "futebol"     ],
    ["fiorentina"             , "time italiano", "futebol"     ],
    ["genoa"                  , "time italiano", "futebol"     ],
    ["psv"                    , "time holandês", "futebol"     ],
    ["ajax"                   , "time holandês", "futebol"     ],
    ["dynamo kiev"            , "time ucraniano", "futebol"    ],
    ["shakhtar donetsk"       , "time ucraniano", "futebol"    ],
    ["fenerbahçe"             , "time turco", "futebol"        ],
    ["beşiktaş"               , "time turco", "futebol"        ],
    ["galatasaray "           , "time turco", "futebol"        ],
    ["olympiakos"             , "time grego", "futebol"        ],
    ["panathinaikos"          , "time grego", "futebol"        ],
    ["aek athens"             , "time grego", "futebol"        ],
    ["zenit"                  , "time russo", "futebol"        ],
    ["lokomotiv"              , "time russo", "futebol"        ],
    ["sartak"                 , "time russo", "futebol"        ],
    ["cska"                   , "time russo", "futebol"        ],
    ["rubin kazan"            , "time russo", "futebol"        ],



 ]




 /*const palavras =    [["vútêmíño" , "time russo", "futebol"        ]]*/
